runtime: nodejs12

handlers:
- url: /favicon\.ico
  static_files: build/favicon.ico
  upload: build/favicon\.ico
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html
